const editorConfig = {
  formWrapper: {
    states: ['hover'],
    properties: {
      background: {},
      color: {},
      padding: {},
      margin: {},
      border: {},
      'box-shadow': {},
      transition: {},
    },
  },
  defaultProps: {
    margin: '0px',
    padding: '0px',
    border: '',
  },
  texfieldStyle: {
    states: ['hover'],
    properties: {
      background: {},
      'background-color': {},
      color: {},
      'font-size': {},
      border: {},
      margin: {},
      padding: {},
      opacity: {},
      size: {},
      'text-align': {},
      'text-decoration': {},
      'text-shadow': {},
      'box-shadow': {},
      'border-radius': {},
      transition: {},
      filter: {},
      'font-family': {},
      'font-weight': {},
      'font-style': {},
      height: {},
      'line-height': {},
      'word-spacing': {},
      'letter-spacing': {},
    },
  },
}
export default editorConfig
