const labelCssProps = {
  background: {},
  border: { width: true, color: true, radius: true },
  color: {},
  'font-size': {},
  'font-weight': {},
  'font-style': {},
  'text-align': {},
  'text-decoration': {},
  'text-shadow': {},
  'box-shadow': {},
  margin: {},
  padding: {},
  opacity: {},
}
const iconCssProps = {
  border: { width: true, color: true, radius: true },
  margin: {},
  padding: {},
  opacity: {},
  weight: {},
  height: {},
  size: {},
  'box-shadow': {},
  filter: {},
}
const editorConfig = {
  formWrapper: {
    states: ['hover'],
    properties: {
      background: {},
      color: {},
      padding: {},
      margin: {},
      border: {},
      'box-shadow': {},
      transition: {},
    },
  },
  defaultProps: {
    margin: '0px',
    padding: '0px',
    border: '',
  },
  texfieldStyle: {
    states: ['hover'],
    properties: {
      background: {},
      'background-color': {},
      color: {},
      'font-size': {},
      border: { width: true, color: true, radius: true },
      margin: {},
      padding: {},
      opacity: {},
      size: {},
      'text-align': {},
      'text-decoration': {},
      'text-shadow': {},
      'box-shadow': {},
      'border-radius': {},
      transition: {},
      filter: {},
      'font-family': {},
      'font-weight': {},
      'font-style': {},
      weight: {},
      height: {},
      'line-height': {},
      'word-spacing': {},
      'letter-spacing': {},
      'z-index': {},
    },
  },
  title: {
    'fld-wrp': {
      states: ['hover'],
      properties: {
        background: {},
        border: { width: true, color: true, radius: true },
        margin: {},
        padding: {},
        opacity: {},
        'box-shadow': {},
        size: {},
      },
    },
    logo: {
      states: ['hover'],
      properties: { ...iconCssProps },
    },
    title: {
      states: ['hover'],
      properties: { ...labelCssProps },
    },
    'sub-titl': {
      states: ['hover'],
      properties: { ...labelCssProps },
    },
    'title-pre-i': {
      states: ['hover'],
      properties: { ...iconCssProps },
    },
    'title-suf-i': {
      states: ['hover'],
      properties: { ...iconCssProps },
    },
    'sub-titl-pre-i': {
      states: ['hover'],
      properties: { ...iconCssProps },
    },
    'sub-titl-suf-i': {
      states: ['hover'],
      properties: { ...iconCssProps },
    },
  },
  titleFieldSubTitle: {},
  titleFieldPrefixIcon: {},
}
export default editorConfig
