export default function repeaterDefaultStyles(formId) {
  return {
    [`.bc${formId}-inner-grid-fld-wrp`]: {
      // display: 'grid',
      'border-style': 'dotted',
      'border-color': `--bc${formId}-a-clr`,
      'border-radius': '4px',
      'border-width': '1px',
      padding: '3px',
    },
    [`.bc${formId}-rpt-fld-wrp`]: {
      display: 'flex',
      'flex-direction': 'column',
    },
    [`.bc${formId}-rpt-wrp`]: {
      display: 'flex',
      'flex-direction': 'row',
      transition: 'all .2s ease',
    },
    [`.bc${formId}-rpt-wrp:nth-child(n+2)`]: {
      'border-top': 'solid',
      'border-color': `var(--bc${formId}-a-clr) !important`,
      'border-width': '1px !important',
      'border-radius': '0px',
      'margin-top': '5px',
    },
    [`.bc${formId}-rpt-grid-wrp`]: {
      width: '100%',
      padding: '5px 10px',
    },
    [`.bc${formId}-pair-btn-wrp`]: {
      display: 'flex',
      'flex-direction': 'row',
      'place-items': 'center',
      padding: '5px',
      'align-self': 'center',
      gap: '5px',
    },
    [`.bc${formId}-rpt-add-btn`]: {
      'font-size': '14px !important',
      padding: '6px',
      // background: 'var(--btn-bg)',
      color: `var(--bc${formId}-btn-txt-clr) !important`,
      'font-weight': '700',
      'border-style': 'solid',
      'border-color': `var(--bc${formId}-fld-bdr-clr)`,
      'border-radius': '20px',
      'border-width': '1px',
      'box-shadow': '0 2px 4px -2px #0006',
      'background-color': `hsla(var(--bc${formId}-btn-bg-h), var(--bc${formId}-btn-bg-s), calc(var(--bc${formId}-btn-bg-l) + 10%), 0.8) !important`,
      cursor: 'pointer',
      'font-family': 'inherit',
      'line-height': '1',
      outline: 'none',
      display: 'flex',
      'justify-content': 'center',
      'align-items': 'center',
      transition: 'background-color 0.2s, transform 0.2s',
    },
    [`.bc${formId}-rpt-add-btn:hover`]: {
      'background-color': `hsl(var(--bc${formId}-btn-bg-h), var(--bc${formId}-btn-bg-s), calc(var(--bc${formId}-btn-bg-l) + 5%)) !important`,
    },
    [`.bc${formId}-rpt-add-btn:disabled`]: {
      cursor: 'not-allowed',
      'pointer-events': 'none',
      opacity: '0.5',
    },
    [`.bc${formId}-rpt-add-btn:focus`]: {
      'box-shadow': `0 0 0 1.5px var(--bc${formId}-a-clr)`,
      'border-color': `var(--bc${formId}-a-clr) !important`,
    },
    [`.bc${formId}-rpt-add-btn-pre-i`]: {
      width: '18px',
      height: '18px',
    },
    [`.bc${formId}-rpt-add-btn-suf-i`]: {
      width: '18px',
    },
    [`.bc${formId}-rpt-rmv-btn`]: {
      'font-size': '14px !important',
      padding: '6px',
      // background: 'var(--btn-bg)',
      color: `var(--bc${formId}-btn-txt-clr) !important`,
      'font-weight': '700',
      'border-style': 'solid',
      'border-color': `var(--bc${formId}-fld-bdr-clr)`,
      'border-radius': '20px',
      'border-width': '1px',
      'box-shadow': '0 2px 4px -2px #0006',
      'background-color': `hsl(var(--bc${formId}-btn-bg-h), var(--bc${formId}-btn-bg-s), calc(var(--bc${formId}-btn-bg-l) + 10%), 0.8) !important`,
      cursor: 'pointer',
      'font-family': 'inherit',
      'line-height': '1',
      outline: 'none',
      display: 'flex',
      'justify-content': 'center',
      'align-items': 'center',
      transition: 'background-color 0.2s, transform 0.2s',
    },
    [`.bc${formId}-rpt-rmv-btn:hover`]: {
      'background-color': `hsl(var(--bc${formId}-btn-bg-h), var(--bc${formId}-btn-bg-s), calc(var(--bc${formId}-btn-bg-l) + 5%)) !important`,
    },
    [`.bc${formId}-rpt-rmv-btn:disabled`]: {
      cursor: 'not-allowed',
      'pointer-events': 'none',
      opacity: '0.5',
    },
    [`.bc${formId}-rpt-rmv-btn:focus`]: {
      'box-shadow': `0 0 0 1.5px var(--bc${formId}-a-clr)`,
      'border-color': `var(--bc${formId}-a-clr) !important`,
    },
    [`.bc${formId}-rpt-rmv-btn-pre-i`]: {
      width: '18px',
      height: '18px',
    },
    [`.bc${formId}-rpt-rmv-btn-suf-i`]: {
      width: '18px',
    },
    [`.bc${formId}-add-to-end-btn-wrp`]: {
      display: 'flex',
      'flex-direction': 'row',
      'align-self': 'start',
      padding: '2px 10px',
    },
    [`.bc${formId}-add-to-end-btn`]: {
      'font-size': '18px',
      padding: '8px 14px',
      'background-color': `hsl(var(--bc${formId}-btn-bg-h), var(--bc${formId}-btn-bg-s), calc(var(--bc${formId}-btn-bg-l) + 10%), 0.8) !important`,
      color: `var(--bc${formId}-btn-txt-clr, #fff)`,
      'font-weight': '700',
      'border-style': 'none',
      'border-width': '0',
      'border-radius': '6px',
      cursor: 'pointer',
      'font-family': 'inherit',
      'line-height': '1',
      outline: 'none',
      display: 'flex',
      gap: '5px',
      'justify-content': 'center',
      'align-items': 'center',
      transition: 'background-color 0.2s, transform 0.2s',
    },
    [`.bc${formId}-add-to-end-btn:hover`]: {
      'background-color': `hsl(var(--bc${formId}-btn-bg-h), var(--bc${formId}-btn-bg-s), calc(var(--bc${formId}-btn-bg-l) + 5%)) !important`,
    },
    [`.bc${formId}-add-to-end-btn:active`]: {
      transform: 'scale(0.95)',
    },
    [`.bc${formId}-add-to-end-btn:disabled`]: {
      cursor: 'not-allowed',
      'pointer-events': 'none',
      opacity: '0.5',
    },
    [`.bc${formId}-add-to-end-btn:focus-visible`]: {
      outline: `2px solid var(--bc${formId}-btn-bg-clr)`,
      'outline-offset': '2px',
      transition: 'outline-offset 0.2s ease',
    },
    [`.bc${formId}-add-to-end-btn:active:focus-visible`]: {
      'outline-offset': 0,
    },
    [`.bc${formId}-add-to-end-btn-pre-i`]: {
      width: '18px',
      filter: 'invert(1)',
    },
    [`.bc${formId}-add-to-end-btn-suf-i`]: {
      width: '18px',
      filter: 'invert(1)',
    },
  }
}
