export const pageSizes = [
  { label: 'A4 (210 x 297mm)', value: 'A4' },
  { label: 'Letter (8.5 x 11in)', value: 'letter' },
  { label: 'Legal (8.5 x 14in)', value: 'Legal' },
  { label: 'Ledger / Tabloid (11 x 17in)', value: 'Ledger' },
  { label: 'Executive (7 x 10in)', value: 'Executive' },
  { label: 'Folio (8.5 x 13in)', value: 'Folio' },
  { label: 'A (111 x 178mm)', value: 'A' },
  { label: 'B (128 x 198mm)', value: 'B' },
  { label: '4A0 (1682 x 2378mm)', value: '4A0' },
  { label: '2A0 (1189 x 1682mm)', value: '2A0' },
  { label: 'A0 (841 x 1189mm)', value: 'A0' },
  { label: 'A1 (594 x 841mm)', value: 'A1' },
  { label: 'A2 (420 x 594mm)', value: 'A2' },
  { label: 'A3 (297 x 420mm)', value: 'A3' },
  { label: 'A5 (148 x 210mm)', value: 'A5' },
  { label: 'A6 (105 x 148mm)', value: 'A6' },
  { label: 'A7 (74 x 105mm)', value: 'A7' },
  { label: 'A8 (52 x 74mm)', value: 'A8' },
  { label: 'A9 (37 x 52mm)', value: 'A9' },
  { label: 'A10 (26 x 37mm)', value: 'A10' },
  { label: 'B0 (1414 x 1000mm)', value: 'B0' },
  { label: 'B1 (1000 x 707mm)', value: 'B1' },
  { label: 'B2 (707 x 500mm)', value: 'B2' },
  { label: 'B3 (500 x 353mm)', value: 'B3' },
  { label: 'B4 (353 x 250mm)', value: 'B4' },
  { label: 'B5 (250 x 176mm)', value: 'B5' },
  { label: 'B6 (176 x 125mm)', value: 'B6' },
  { label: 'B7 (125 x 88mm)', value: 'B7' },
  { label: 'B8 (88 x 62mm)', value: 'B8' },
  { label: 'B9 (62 x 44mm)', value: 'B9' },
  { label: 'B10 (44 x 31mm)', value: 'B10' },
  { label: 'C0 (1297 x 917mm)', value: 'C0' },
  { label: 'C1 (917 x 648mm)', value: 'C1' },
  { label: 'C2 (648 x 458mm)', value: 'C2' },
  { label: 'C3 (458 x 324mm)', value: 'C3' },
  { label: 'C4 (324 x 229mm)', value: 'C4' },
  { label: 'C5 (229 x 162mm)', value: 'C5' },
  { label: 'C6 (162 x 114mm)', value: 'C6' },
  { label: 'C7 (114 x 81mm)', value: 'C7' },
  { label: 'C8 (81 x 57mm)', value: 'C8' },
  { label: 'C9 (57 x 40mm)', value: 'C9' },
  { label: 'C10 (40 x 28mm)', value: 'C10' },
  { label: 'RA0 (860 x 1220mm)', value: 'RA0' },
  { label: 'RA1 (610 x 860mm)', value: 'RA1' },
  { label: 'RA2 (430 x 610mm)', value: 'RA2' },
  { label: 'RA3 (305 x 430mm)', value: 'RA3' },
  { label: 'RA4 (215 x 305mm)', value: 'RA4' },
  { label: 'SRA0 (900 x 1280mm)', value: 'SRA0' },
  { label: 'SRA1 (640 x 900mm)', value: 'SRA1' },
  { label: 'SRA2 (450 x 640mm)', value: 'SRA2' },
  { label: 'SRA3 (320 x 450mm)', value: 'SRA3' },
  { label: 'SRA4 (225 x 320mm)', value: 'SRA4' },
  { label: 'DEMY (135 x 216mm)', value: 'DEMY' },
  { label: 'ROYAL (135 x 216mm)', value: 'ROYAL' },
]

export const fontList = [
  { name: 'AboriginalSansREGULAR', font: 'AboriginalSansREGULAR.ttf' },
  { name: 'Abyssinica_SIL', font: 'Abyssinica_SIL.ttf' },
  { name: 'Aegean', font: 'Aegean.otf' },
  { name: 'Aegyptus', font: 'Aegyptus.otf' },
  { name: 'Akkadian', font: 'Akkadian.otf' },
  { name: 'DBSILBR', font: 'DBSILBR.ttf' },
  { name: 'DejaVuSans-Bold', font: 'DejaVuSans-Bold.ttf' },
  { name: 'DejaVuSans-BoldOblique', font: 'DejaVuSans-BoldOblique.ttf' },
  { name: 'DejaVuSans-Oblique', font: 'DejaVuSans-Oblique.ttf' },
  { name: 'DejaVuSans', font: 'DejaVuSans.ttf' },
  { name: 'DejaVuSansCondensed-Bold', font: 'DejaVuSansCondensed-Bold.ttf' },
  { name: 'DejaVuSansCondensed-BoldOblique', font: 'DejaVuSansCondensed-BoldOblique.ttf' },
  { name: 'DejaVuSansCondensed-Oblique', font: 'DejaVuSansCondensed-Oblique.ttf' },
  { name: 'DejaVuSansCondensed', font: 'DejaVuSansCondensed.ttf' },
  { name: 'DejaVuSansMono-Bold', font: 'DejaVuSansMono-Bold.ttf' },
  { name: 'DejaVuSansMono-BoldOblique', font: 'DejaVuSansMono-BoldOblique.ttf' },
  { name: 'DejaVuSansMono-Oblique', font: 'DejaVuSansMono-Oblique.ttf' },
  { name: 'DejaVuSansMono', font: 'DejaVuSansMono.ttf' },
  { name: 'DejaVuSerif-Bold', font: 'DejaVuSerif-Bold.ttf' },
  { name: 'DejaVuSerif-BoldItalic', font: 'DejaVuSerif-BoldItalic.ttf' },
  { name: 'DejaVuSerif-Italic', font: 'DejaVuSerif-Italic.ttf' },
  { name: 'DejaVuSerif', font: 'DejaVuSerif.ttf' },
  { name: 'DejaVuSerifCondensed-Bold', font: 'DejaVuSerifCondensed-Bold.ttf' },
  { name: 'DejaVuSerifCondensed-BoldItalic', font: 'DejaVuSerifCondensed-BoldItalic.ttf' },
  { name: 'DejaVuSerifCondensed-Italic', font: 'DejaVuSerifCondensed-Italic.ttf' },
  { name: 'DejaVuSerifCondensed', font: 'DejaVuSerifCondensed.ttf' },
  { name: 'Dhyana-Bold', font: 'Dhyana-Bold.ttf' },
  { name: 'Dhyana-Regular', font: 'Dhyana-Regular.ttf' },
  { name: 'FreeMono', font: 'FreeMono.ttf' },
  { name: 'FreeMonoBold', font: 'FreeMonoBold.ttf' },
  { name: 'FreeMonoBoldOblique', font: 'FreeMonoBoldOblique.ttf' },
  { name: 'FreeMonoOblique', font: 'FreeMonoOblique.ttf' },
  { name: 'FreeSans', font: 'FreeSans.ttf' },
  { name: 'FreeSansBold', font: 'FreeSansBold.ttf' },
  { name: 'FreeSansBoldOblique', font: 'FreeSansBoldOblique.ttf' },
  { name: 'FreeSansOblique', font: 'FreeSansOblique.ttf' },
  { name: 'FreeSerif', font: 'FreeSerif.ttf' },
  { name: 'FreeSerifBold', font: 'FreeSerifBold.ttf' },
  { name: 'FreeSerifBoldItalic', font: 'FreeSerifBoldItalic.ttf' },
  { name: 'FreeSerifItalic', font: 'FreeSerifItalic.ttf' },
  { name: 'Garuda-Bold', font: 'Garuda-Bold.ttf' },
  { name: 'Garuda-BoldOblique', font: 'Garuda-BoldOblique.ttf' },
  { name: 'Garuda-Oblique', font: 'Garuda-Oblique.ttf' },
  { name: 'Garuda', font: 'Garuda.ttf' },
  { name: 'Jomolhari', font: 'Jomolhari.ttf' },
  { name: 'KhmerOS', font: 'KhmerOS.ttf' },
  { name: 'LateefRegOT', font: 'LateefRegOT.ttf' },
  { name: 'Lohit-Kannada', font: 'Lohit-Kannada.ttf' },
  { name: 'Padauk-book', font: 'Padauk-book.ttf' },
  { name: 'Pothana2000', font: 'Pothana2000.ttf' },
  { name: 'Quivira', font: 'Quivira.otf' },
  { name: 'Sun-ExtA', font: 'Sun-ExtA.ttf' },
  { name: 'Sun-ExtB', font: 'Sun-ExtB.ttf' },
  { name: 'SundaneseUnicode', font: 'SundaneseUnicode-1.0.5.ttf' },
  { name: 'SyrCOMEdessa', font: 'SyrCOMEdessa.otf' },
  { name: 'TaameyDavidCLM-Medium', font: 'TaameyDavidCLM-Medium.ttf' },
  { name: 'TaiHeritagePro', font: 'TaiHeritagePro.ttf' },
  { name: 'Tharlon-Regular', font: 'Tharlon-Regular.ttf' },
  { name: 'UnBatang_0613', font: 'UnBatang_0613.ttf' },
  { name: 'Uthman', font: 'Uthman.otf' },
  { name: 'XB Riyaz', font: 'XB Riyaz.ttf' },
  { name: 'XB RiyazBd', font: 'XB RiyazBd.ttf' },
  { name: 'XB RiyazBdIt', font: 'XB RiyazBdIt.ttf' },
  { name: 'XB RiyazIt', font: 'XB RiyazIt.ttf' },
  { name: 'ZawgyiOne', font: 'ZawgyiOne.ttf' },
  { name: 'ayar', font: 'ayar.ttf' },
  { name: 'damase_v.2', font: 'damase_v.2.ttf' },
  { name: 'kaputaunicode', font: 'kaputaunicode.ttf' },
  { name: 'lannaalif-v1-03', font: 'lannaalif-v1-03.ttf' },
  { name: 'ocrb10', font: 'ocrb10.ttf' },
]
