import { __ } from '../i18nwrap'

const proHelperData = {
  'advanced-file-up': { heading: __('Advanced File Upload Field'), featureText: __('Advanced File Upload Field') },
  paypal: { heading: __('PayPal Payment Field'), featureText: __('PayPal Payment Field') },
  razorpay: { heading: __('Razorpay Payment Field'), featureText: __('Razorpay Payment Field') },
  leadingIcon: { heading: __('Leading Icon'), featureText: __('Leading Icon') },
  trailingIcon: { heading: __('Trailing Icon'), featureText: __('Trailing Icon') },
  inputIcons: { heading: __('Input Icons'), featureText: __('Input Icons') },
  defaultValue: { heading: __('Default Value'), featureText: __('Default Value') },
  suggestion: { heading: __('Suggestions'), featureText: __('Suggestions') },
  inputMode: { heading: __('Input Mode'), featureText: __('Input Mode') },
  regexPattern: { heading: __('Regex Pattern'), featureText: __('Regex Pattern') },
  hidden: { heading: __('Hidden'), featureText: __('Hidden') },
  readOnly: { heading: __('Read Only'), featureText: __('Read Only') },
  disabled: { heading: __('Disabled'), featureText: __('Disabled') },
  entryUnique: { heading: __('Unique Entry'), featureText: __('Unique Entry') },
  userUnique: { heading: __('User Unique'), featureText: __('User Unique') },
  validation: { heading: __('Input Validation'), featureText: __('Input Validation') },
  maximumOption: { heading: __('Maximum Option Validation'), featureText: __('Maximum Option Validation') },
  mimimumOption: { heading: __('Minimum Option Validation'), featureText: __('Minimum Option Validation') },
  optionColumn: { heading: __('Option Column'), featureText: __('Option Column') },
  otherOption: { heading: __('Other Option'), featureText: __('Other Option') },
  searchPlaceholder: { heading: __('Search Placeholder Modify'), featureText: __('Search Placeholder Modify') },
  selectedOptImage: { heading: __('Selected Option Image'), featureText: __('Showing Selected Option Image') },
  optionIcon: { heading: __('Option Icon/Image'), featureText: __('Showing Icon/Image in option') },
  minMaxOpt: { heading: __('Minimum and Maximum Option'), featureText: __('Minimum and Maximum Option validation') },
  listHeight: { heading: __('List Height'), featureText: __('Option List Height') },
  detectCountryByIp: { heading: __('Detect Country by IP'), featureText: __('Detect Country by IP') },
  detectCountryByGeo: { heading: __('Detect Country by Geo Location'), featureText: __('Detect Country by Geo Location') },
  optionList: { heading: __('Multiple Option List'), featureText: __('Multiple Option List') },
  minMaxValue: { heading: __('Minimum and Maximum Value'), featureText: __('Minimum and Maximum Value Validation') },
  inputFormatOptions: { heading: __('Input Format Options'), featureText: __('Input Format Options') },
  valueFormatOptions: { heading: __('Value Format Options'), featureText: __('Value Format Options') },
  countryNotFoundText: { heading: __('Country Not Found Text'), featureText: __('Country Not Found Text Modify') },
  currencyNotFoundText: { heading: __('Currency Not Found Text'), featureText: __('Currency Not Found Text Modify') },
}

export default proHelperData
