const tableStyles = {
  caption: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
  tableWrp: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
  table: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
    width: '',
  },
  tHead: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
  oddRow: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
  evenRow: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
  editBtn: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
  viewBtn: {
    background: {
      'background-color': true,
    },
    border: {
      'border-style': true,
      'border-color': true,
      'border-width': true,
      'border-radius': true,
    },
    color: '',
    'font-size': '',
    'font-weight': '',
    'font-style': '',
    'text-align': '',
    margin: '5px',
    padding: '5px',
  },
}

export default tableStyles
