export default {
  name: 'Academic Advisor Meeting Form',
  theme: 'bitformDefault',
  formInfo: {
    formName: 'Academic Advisor Meeting Form',
  },
  layouts: {
    lg: [
      {
        w: 60,
        h: 28,
        x: 0,
        y: 0,
        i: 'fld_key-5',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 0,
        y: 28,
        i: 'fld_key-2',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 30,
        y: 28,
        i: 'fld_key-3',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 105,
        i: 'fld_key-4',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 28,
        x: 0,
        y: 182,
        i: 'fld_key-6',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 0,
        y: 210,
        i: 'fld_key-7',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 30,
        y: 210,
        i: 'fld_key-8',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 287,
        i: 'fld_key-9',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 31,
        x: 0,
        y: 364,
        i: 'fld_key-14',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 103,
        x: 0,
        y: 395,
        i: 'fld_key-10',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 65,
        x: 0,
        y: 498,
        i: 'fld_key-11',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 65,
        x: 0,
        y: 563,
        i: 'fld_key-12',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 98,
        x: 0,
        y: 628,
        i: 'fld_key-13',
        minW: 9,
        moved: false,
        static: false,
        resizeHandles: [
          'se',
          'e',
        ],
      },
      {
        w: 60,
        h: 54,
        x: 0,
        y: 726,
        i: 'fld_key-1',
        moved: false,
        static: false,
      },
    ],
  },
  fields: {
    'fld_key-1': {
      typ: 'button',
      btnSiz: 'md',
      btnTyp: 'submit',
      txt: 'Submit',
      icn: {
        pos: '',
        url: '',
      },
      valid: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-1',
    },
    'fld_key-2': {
      typ: 'text',
      lbl: 'First Name',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-2',
    },
    'fld_key-3': {
      typ: 'text',
      lbl: 'Last Name',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-3',
    },
    'fld_key-4': {
      typ: 'email',
      lbl: 'Email',
      phHide: false,
      pattern: '^[^$_bf_$s@]+@[^$_bf_$s@]+$_bf_$.[^$_bf_$s@]+$',
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        invalid: {
          dflt: '<p style="margin:0">Please, Enter a valid email address.</p>',
          show: true,
        },
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
          custom: true,
          msg: '<p style="margin:0">Please enter your email.</p>',
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-4',
    },
    'fld_key-5': {
      typ: 'title',
      adminLbl: 'Title',
      adminLblHide: true,
      titleImg: '',
      logoHide: true,
      title: 'Student Information',
      titleHide: false,
      subtitleHide: true,
      titleTag: 'h4',
      subTitleTag: 'h5',
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-5',
    },
    'fld_key-6': {
      typ: 'title',
      adminLbl: 'Title',
      adminLblHide: true,
      titleImg: '',
      logoHide: true,
      title: 'Advisor Information',
      titleHide: false,
      subtitleHide: true,
      titleTag: 'h4',
      subTitleTag: 'h5',
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-6',
    },
    'fld_key-7': {
      typ: 'text',
      lbl: 'First Name',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-7',
    },
    'fld_key-8': {
      typ: 'text',
      lbl: 'Last Name',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-8',
    },
    'fld_key-9': {
      typ: 'email',
      lbl: 'Email',
      phHide: false,
      pattern: '^[^$_bf_$s@]+@[^$_bf_$s@]+$_bf_$.[^$_bf_$s@]+$',
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        invalid: {
          dflt: '<p style="margin:0">Please, Enter a valid email address.</p>',
          show: true,
        },
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
          custom: true,
          msg: '<p style="margin:0">Please enter your email.</p>',
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-9',
    },
    'fld_key-10': {
      typ: 'radio',
      lbl: 'Reason For Meetting',
      round: true,
      opt: [
        {
          lbl: 'Scheduling Courses',
        },
        {
          lbl: 'Drop/Add Courses',
        },
        {
          lbl: 'Discuss Academic Progress',
        },
        {
          lbl: 'Interest in Transferring',
        },
      ],
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      optionCol: '2',
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-10',
    },
    'fld_key-11': {
      typ: 'check',
      lbl: 'Best Days to Meet (check all that apply) ',
      opt: [
        {
          lbl: 'Monday',
        },
        {
          lbl: 'Tuesday',
        },
        {
          lbl: 'Wednesday',
        },
        {
          lbl: 'Thursday',
        },
        {
          lbl: 'Friday',
        },
      ],
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      optionCol: '5',
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-11',
    },
    'fld_key-12': {
      typ: 'check',
      lbl: 'Best Times to Meet (check all that apply)',
      opt: [
        {
          lbl: 'Morning',
        },
        {
          lbl: 'Mid-morning',
        },
        {
          lbl: 'Afternoon',
        },
        {
          lbl: 'Mid-afternoon',
        },
        {
          lbl: 'Evening',
        },
      ],
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      optionCol: '5',
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-12',
    },
    'fld_key-13': {
      typ: 'textarea',
      lbl: 'Comment or Message',
      ph: 'Placeholder...',
      phHide: true,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'textarea-157-13',
    },
    'fld_key-14': {
      typ: 'divider',
      adminLbl: 'Divider',
      adminLblHide: true,
      valid: {},
      divider: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-14',
    },
  },
}
