export default {
  name: 'Constant Contact GDPR Form Template',
  theme: 'bitformDefault',
  formInfo: {
    formName: 'Constant Contact GDPR Form Template',
  },
  layouts: {
    lg: [
      {
        w: 30,
        h: 77,
        x: 0,
        y: 0,
        i: 'fld_key-2',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 30,
        y: 0,
        i: 'fld_key-3',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 77,
        i: 'fld_key-4',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 98,
        x: 0,
        y: 154,
        i: 'fld_key-5',
        minW: 9,
        moved: false,
        static: false,
        resizeHandles: [
          'se',
          'e',
        ],
      },
      {
        w: 60,
        h: 28,
        x: 0,
        y: 252,
        i: 'fld_key-6',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 38,
        x: 0,
        y: 280,
        i: 'fld_key-7',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 28,
        x: 0,
        y: 318,
        i: 'fld_key-8',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 38,
        x: 0,
        y: 346,
        i: 'fld_key-9',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 54,
        x: 0,
        y: 384,
        i: 'fld_key-1',
        moved: false,
        static: false,
      },
    ],
  },
  fields: {
    'fld_key-1': {
      typ: 'button',
      btnSiz: 'md',
      btnTyp: 'submit',
      txt: 'Submit',
      icn: {
        pos: '',
        url: '',
      },
      valid: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-1',
    },
    'fld_key-2': {
      typ: 'text',
      lbl: 'First Name',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-2',
    },
    'fld_key-3': {
      typ: 'text',
      lbl: 'Last Name',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-3',
    },
    'fld_key-4': {
      typ: 'email',
      lbl: 'Email',
      phHide: false,
      pattern: '^[^$_bf_$s@]+@[^$_bf_$s@]+$_bf_$.[^$_bf_$s@]+$',
      valid: {},
      err: {
        invalid: {
          dflt: '<p style="margin:0">Please, Enter a valid email address.</p>',
          show: true,
        },
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
          custom: true,
          msg: '<p style="margin:0">Please enter your email.</p>',
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-4',
    },
    'fld_key-5': {
      typ: 'textarea',
      lbl: 'Message',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-5',
    },
    'fld_key-6': {
      typ: 'title',
      adminLbl: 'Title',
      adminLblHide: true,
      titleImg: '',
      logoHide: true,
      title: 'GDPR Agreement',
      titleHide: false,
      subtitleHide: true,
      titleTag: 'h4',
      subTitleTag: 'h5',
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-6',
    },
    'fld_key-7': {
      typ: 'decision-box',
      adminLblHide: true,
      lbl: '<p style="margin: 0;"><span style="font-size: 12pt;">I consent to having this website store my submitted information so they can respond to my inquiry.</span></p>',
      msg: {
        checked: 'Accepted',
        unchecked: 'Rejected',
      },
      valid: {
        req: true,
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-7',
      adminLbl: 'Decision box',
    },
    'fld_key-8': {
      typ: 'title',
      adminLbl: 'Title',
      adminLblHide: true,
      titleImg: '',
      logoHide: true,
      title: 'Newsletter',
      titleHide: false,
      subtitleHide: true,
      titleTag: 'h4',
      subTitleTag: 'h5',
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-8',
    },
    'fld_key-9': {
      typ: 'decision-box',
      adminLbl: 'Decision Box',
      adminLblHide: true,
      lbl: "<p style=\"margin: 0;\"><span style=\"color: rgba(0, 0, 0, 0.85); font-family: GeneralSans-Variable, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;\">Yes, sign me up to the newsletter</span></p>",
      msg: {
        checked: 'Accepted',
        unchecked: 'Rejected',
      },
      valid: {
        req: true,
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-9',
    },
  },

}
