export default {
  name: 'Grade Book Form Template',
  theme: 'bitformDefault',
  formInfo: {
    formName: 'Grade Book Form Template',
  },
  fields: {
    'fld_key-1': {
      typ: 'button',
      btnSiz: 'md',
      btnTyp: 'submit',
      txt: 'Submit',
      icn: {
        pos: '',
        url: '',
      },
      valid: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-1',
    },
    'fld_key-2': {
      typ: 'text',
      phHide: false,
      valid: {
        hideLbl: false,
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-2',
      hlpTxtHide: false,
      lbl: 'Firstname',
    },
    'fld_key-3': {
      typ: 'text',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-3',
      lbl: 'Lastname',
    },
    'fld_key-4': {
      typ: 'text',
      lbl: 'Student ID',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-4',
    },
    'fld_key-5': {
      typ: 'text',
      lbl: 'Assignment name',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-5',
    },
    'fld_key-6': {
      typ: 'html-select',
      lbl: 'Status',
      opt: [
        {
          lbl: '--Select Option--',
          disabled: true,
          check: true,
        },
        {
          lbl: 'Late',
        },
        {
          lbl: 'Complete',
        },
      ],
      ph: 'Select an option...',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-6',
    },
    'fld_key-7': {
      typ: 'html-select',
      lbl: 'Grade',
      opt: [
        {
          lbl: 'A',
        },
        {
          lbl: 'B',
        },
        {
          lbl: 'C',
        },
        {
          lbl: 'D',
        },
        {
          lbl: 'F',
        },
      ],
      ph: 'Select an option...',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-7',
    },
    'fld_key-8': {
      typ: 'textarea',
      lbl: 'Comments',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-8',
    },
    'fld_key-9': {
      typ: 'divider',
      adminLbl: 'Divider',
      adminLblHide: true,
      valid: {},
      divider: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-9',
    },
    'fld_key-10': {
      typ: 'text',
      phHide: false,
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
        hideLbl: false,
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-10',
      hlpTxtHide: false,
      lbl: 'Firstname',
    },
    'fld_key-11': {
      typ: 'text',
      phHide: false,
      valid: {
        hideLbl: false,
      },
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-11',
      hlpTxtHide: false,
      lbl: 'Lastname',
    },
    'fld_key-12': {
      typ: 'email',
      lbl: 'Email',
      phHide: false,
      pattern: '^[^$_bf_$s@]+@[^$_bf_$s@]+$_bf_$.[^$_bf_$s@]+$',
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        invalid: {
          dflt: '<p style="margin:0">Please, Enter a valid email address.</p>',
          show: true,
        },
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
          custom: true,
          msg: '<p style="margin:0">Please enter your email.</p>',
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-12',
    },
    'fld_key-13': {
      typ: 'title',
      adminLbl: 'Title',
      adminLblHide: true,
      titleImg: '',
      logoHide: true,
      title: 'Student Information',
      titleHide: false,
      subtitleHide: true,
      titleTag: 'h4',
      subTitleTag: 'h5',
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-13',
    },
    'fld_key-14': {
      typ: 'title',
      adminLbl: 'Title',
      adminLblHide: true,
      titleImg: '',
      logoHide: true,
      title: 'Teacher Information',
      titleHide: false,
      subtitleHide: true,
      titleTag: 'h4',
      subTitleTag: 'h5',
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-14',
    },
  },
  layouts: {
    lg: [
      {
        w: 60,
        h: 28,
        x: 0,
        y: 0,
        i: 'fld_key-13',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 0,
        y: 28,
        i: 'fld_key-2',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 30,
        y: 28,
        i: 'fld_key-3',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 105,
        i: 'fld_key-4',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 182,
        i: 'fld_key-5',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 259,
        i: 'fld_key-6',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 336,
        i: 'fld_key-7',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 98,
        x: 0,
        y: 413,
        i: 'fld_key-8',
        minW: 9,
        moved: false,
        static: false,
        resizeHandles: [
          'se',
          'e',
        ],
      },
      {
        w: 60,
        h: 31,
        x: 0,
        y: 511,
        i: 'fld_key-9',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 28,
        x: 0,
        y: 542,
        i: 'fld_key-14',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 0,
        y: 570,
        i: 'fld_key-10',
        moved: false,
        static: false,
      },
      {
        w: 30,
        h: 77,
        x: 30,
        y: 570,
        i: 'fld_key-11',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 647,
        i: 'fld_key-12',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 54,
        x: 0,
        y: 724,
        i: 'fld_key-1',
        moved: false,
        static: false,
      },
    ],
  },
}
