export default {
  name: 'Meeting Room Registration Form',
  theme: 'bitformDefault',
  formInfo: {
    formName: 'Meeting Room Registration Form',
  },
  fields: {
    'fld_key-1': {
      typ: 'button',
      btnSiz: 'md',
      btnTyp: 'submit',
      txt: 'Submit',
      icn: {
        pos: '',
        url: '',
      },
      valid: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-1',
    },
    'fld_key-2': {
      typ: 'section',
      lbl: 'Name',
      layout: {
        autoHeight: 1,
      },
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-2',
    },
    'fld_key-3': {
      typ: 'text',
      phHide: false,
      valid: {
        hideLbl: true,
      },
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-3',
      helperTxt: 'Last',
      hlpTxtHide: true,
    },
    'fld_key-4': {
      typ: 'text',
      phHide: false,
      valid: {
        hideLbl: true,
      },
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-4',
      helperTxt: 'First',
      hlpTxtHide: true,
    },
    'fld_key-5': {
      typ: 'email',
      lbl: 'Email',
      phHide: false,
      pattern: '^[^$_bf_$s@]+@[^$_bf_$s@]+$_bf_$.[^$_bf_$s@]+$',
      valid: {},
      err: {
        invalid: {
          dflt: '<p style="margin:0">Please, Enter a valid email address.</p>',
          show: true,
        },
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
          custom: true,
          msg: '<p style="margin:0">Please enter your email.</p>',
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-5',
    },
    'fld_key-6': {
      typ: 'text',
      phHide: false,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-6',
      lbl: 'Department',
    },
    'fld_key-7': {
      typ: 'radio',
      lbl: 'Which room would you like to reserve?',
      round: true,
      opt: [
        {
          lbl: 'Option 1',
        },
        {
          lbl: 'Option 2',
        },
        {
          lbl: 'Option 3',
        },
      ],
      valid: {
        req: true,
        reqShow: true,
        reqPos: 'after',
      },
      err: {
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
        },
      },
      optionCol: 1,
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-7',
    },
    'fld_key-8': {
      typ: 'check',
      lbl: 'Check Boxs',
      opt: [
        {
          lbl: '8:00-9:00 am',
        },
        {
          lbl: '9:00-10:00 am',
        },
        {
          lbl: '10:00-11:00 am',
        },
        {
          lbl: '11:00-12:00 pm',
        },
        {
          lbl: '12:00-01:00 pm',
        },
        {
          lbl: '01:00-02:00 pm',
        },
        {
          lbl: '02:00-03:00 pm',
        },
        {
          lbl: '03:00-04:00 pm',
        },
        {
          lbl: '04:00-05:00 pm',
        },
      ],
      valid: {},
      err: {},
      optionCol: 1,
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-8',
    },
    'fld_key-9': {
      typ: 'textarea',
      lbl: 'Questions or Comments',
      ph: 'Placeholder...',
      phHide: true,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-9',
    },
  },
  layouts: {
    lg: [
      {
        w: 60,
        h: 121,
        x: 0,
        y: 0,
        i: 'fld_key-2',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 121,
        i: 'fld_key-5',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 77,
        x: 0,
        y: 198,
        i: 'fld_key-6',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 131,
        x: 0,
        y: 275,
        i: 'fld_key-7',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 329,
        x: 0,
        y: 406,
        i: 'fld_key-8',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 98,
        x: 0,
        y: 735,
        i: 'fld_key-9',
        minW: 9,
        moved: false,
        static: false,
        resizeHandles: [
          'se',
          'e',
        ],
      },
      {
        w: 60,
        h: 54,
        x: 0,
        y: 833,
        i: 'fld_key-1',
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
  },
  nestedLayouts: {
    'fld_key-2': {
      lg: [
        {
          w: 30,
          h: 76,
          x: 0,
          y: 0,
          i: 'fld_key-4',
          moved: false,
          static: false,
        },
        {
          w: 30,
          h: 76,
          x: 30,
          y: 0,
          i: 'fld_key-3',
          moved: false,
          static: false,
        },
      ],
      md: [],
      sm: [],
    },
  },

}
