export default {
  name: 'Repeater Field Test Form',
  theme: 'bitformDefault',
  formInfo: {
    formName: 'Repeater Field Test Form',
  },
  fields: {
    'fld_key-1': {
      typ: 'button',
      btnSiz: 'md',
      btnTyp: 'submit',
      txt: 'Submit',
      icn: {
        pos: '',
        url: '',
      },
      valid: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-1',
    },
    'fld_key-2': {
      typ: 'repeater',
      lbl: 'Repeater',
      layout: {
        autoHeight: 1,
      },
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      addBtn: {
        show: true,
        btnTyp: 'button',
        btnSiz: 'md',
        txt: '',
        icn: {
          pos: '',
          url: '',
        },
      },
      addBtnPreIcn: 'http://bitform.xyz/wp-content/plugins/bitform/assets/../static/repeater/plusicon.svg',
      removeBtn: {
        show: true,
        btnTyp: 'button',
        btnSiz: 'md',
        txt: '',
        icn: {
          pos: '',
          url: '',
        },
      },
      removeBtnPreIcn: 'http://bitform.xyz/wp-content/plugins/bitform/assets/../static/repeater/minusicon.svg',
      addToEndBtn: {
        btnAlignment: 'start',
        show: false,
        btnTyp: 'button',
        btnSiz: 'md',
        txt: 'Add New',
        icn: {
          pos: '',
          url: '',
        },
      },
      addToEndBtnPreIcn: 'http://bitform.xyz/wp-content/plugins/bitform/assets/../static/repeater/plusicon.svg',
      btnPosition: 'row',
      btnAlignment: 'center',
      btnView: 'row',
      repeatDirecton: 'column',
      fieldName: 'fld_key-2',
    },
    'fld_key-3': {
      typ: 'text',
      ph: 'Placeholder...',
      phHide: true,
      valid: {},
      err: {},
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-3',
      lbl: 'Name',
    },
    'fld_key-4': {
      typ: 'number',
      lbl: 'ID',
      ph: 'e.g. 123',
      phHide: true,
      valid: {},
      err: {
        invalid: {
          dflt: '<p style="margin:0">Number is invalid</p>',
          show: true,
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-4',
    },
    'fld_key-5': {
      typ: 'email',
      lbl: 'Email',
      ph: 'example@mail.com',
      phHide: true,
      pattern: '^[^$_bf_$s@]+@[^$_bf_$s@]+$_bf_$.[^$_bf_$s@]+$',
      valid: {},
      err: {
        invalid: {
          dflt: '<p style="margin:0">Please, Enter a valid email address.</p>',
          show: true,
        },
        req: {
          dflt: '<p style="margin:0">This field is required</p>',
          show: true,
          custom: true,
          msg: '<p style="margin:0">Please enter your email.</p>',
        },
      },
      customClasses: {},
      customAttributes: {},
      fieldName: 'fld_key-5',
    },
  },
  layouts: {
    lg: [
      {
        w: 60,
        h: 77,
        x: 0,
        y: 0,
        i: 'fld_key-5',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 122,
        x: 0,
        y: 77,
        i: 'fld_key-2',
        moved: false,
        static: false,
      },
      {
        w: 60,
        h: 54,
        x: 0,
        y: 199,
        i: 'fld_key-1',
        moved: false,
        static: false,
      },
    ],
    md: [],
    sm: [],
  },
  nestedLayouts: {
    'fld_key-2': {
      lg: [
        {
          w: 25,
          h: 77,
          x: 0,
          y: 0,
          i: 'fld_key-3',
          moved: false,
          static: false,
        },
        {
          w: 25,
          h: 77,
          x: 30,
          y: 0,
          i: 'fld_key-4',
          moved: false,
          static: false,
        },
      ],
      md: [],
      sm: [],
    },
  },

}
