const optionmenu = {
  dropdownWrp: {
    pn: 'relative',
    w: 30,
    h: 30,
  },
  menuBtn: {
    dy: 'grid',
    g: 'center',
    w: 30,
    h: 30,
    oe: 0,
    bc: 'var(--white-100)',
    b: 'none',
    brs: '50%',
    curp: 1,
    zx: 2,
    pn: 'absolute',
    tp: 0,
    rt: 0,
    cr: 'black',
    '&:hover': { bd: 'var(--white-0-97)' },
    '&focus-visible': { bs: '0 0 0 2px var(--b-50) inset' },
  },
  btnActive: { bs: 'none' },
  dropDown: {
    pn: 'absolute',
    tp: 0,
    rt: 0,
    bc: 'var(--white-100)',
    bs: '0 1px 6px -3px var(--white-0-31)',
    w: 30,
    h: 30,
    brs: 20,
    ow: 'hidden',
    tn: 'width 400ms cubic-bezier(0.37, -0.79, 0.57, 0.55), height 400ms cubic-bezier(0.37, -0.79, 0.57, 0.55), border-radius 400ms ease,padding 400ms ease, box-shadow 400ms ease',
  },
  dropDownShow: {
    p: '10px !important',
    brs: '12px !important',
    bs: '0 3px 9px -4px var(--white-0-0-17), 0 3px 25px -7px var(--white-0-86)',
    tn: 'width 400ms cubic-bezier(0.16, 0.04, 0.58, 1.47), height 400ms cubic-bezier(0.16, 0.04, 0.58, 1.47), border-radius 400ms ease, padding 400ms ease',
    '&.drop-down-show .drop-down-title': { oy: 1, tdy: '300ms' },
    '&.drop-down-show .items-wrp': {
      tn: 'opacity 400ms ease 400ms',
      oy: 1,
      vy: 'visible',
    },
  },
  dropDownTitle: {
    tn: 'opacity 400ms',
    tdy: '200ms',
    oy: 0,
    bb: '1px solid var(--white-0-97)',
    pb: 5,
    mb: 5,
    fw: 600,
    cr: 'var(--b-54-12)',
  },
  itemsWrp: {
    vy: 'hidden',
    tn: 'opacity 200ms ease, visibility 0s ease 300ms',
    m: '0',
    oy: 0,
    '& :is(button, a)': {
      cr: 'var(--b-37-18)',
      flx: 'align-center',
      b: 'none',
      bd: 'transparent',
      fw: 500,
      curp: 1,
      h: 30,
      p: 5,
      m: 0,
      brs: 8,
      tn: 'background 400ms',
      oe: 'none',
      w: '100%',
      '&:focus-visible': { bs: '0 0 0 2px var(--b-50)' },
      '&:hover': {
        bd: 'var(--b-79-96)',
        cr: 'var(--b-37-18)',
      },
    },

  },
  hamburger: {
    bc: 'transparent',
    b: 'none',
    curp: 1,
    dy: 'flex',
    p: '0',
    '&.hamburger.open .line': { stroke: 'var(--white-0-31)' },
    '&.hamburger .line1': { strokeDasharray: '60 207', strokeWidth: 6 },
    '&.hamburger .line2': { strokeDasharray: '60 60', strokeWidth: 6 },
    '&.hamburger .line3': { strokeDasharray: '60 207', strokeWidth: 6 },
    '&.hamburger.open .line1': {
      strokeDasharray: '90 207',
      strokeDashoffset: -134,
      strokeWidth: 6,
    },
    '&.hamburger.open .line2': {
      strokeDasharray: '1 60',
      strokeDashoffset: -30,
      strokeWidth: 6,
    },
    '&.hamburger.open .line3': {
      strokeDasharray: '90 207',
      strokeDashoffset: -134,
      strokeWidth: 6,
    },
  },
  line: {
    fill: 'none',
    stroke: 'var(--b-50)',
    strokeWidth: 10,
    tn: 'stroke-dasharray 600ms cubic-bezier(0.4, 0, 0.2, 1), stroke-dashoffset 600ms cubic-bezier(0.4, 0, 0.2, 1), stroke 500ms',
  },
}

export default optionmenu
