/* eslint-disable max-len */
export const packagesFileLists = {
  // package-name: [file-names]
  'bit-advanced-file-up-field': ['bit-advanced-file-up-field'],
  'bit-conditionals': ['bit-conditionals'],
  'bit-country-field': ['bit-country-field'],
  'bit-currency-field': ['bit-currency-field'],
  'bit-file-up-field': ['bit-file-up-field'],
  'bit-filepond': ['bit-filepond'],
  'bit-filepond-plugin-file-validate-size': ['bit-filepond-plugin-file-validate-size'],
  'bit-filepond-plugin-file-validate-type': ['bit-filepond-plugin-file-validate-type'],
  'bit-filepond-plugin-image-crop': ['bit-filepond-plugin-image-crop'],
  'bit-filepond-plugin-image-preview': ['bit-filepond-plugin-image-preview'],
  'bit-filepond-plugin-image-resize': ['bit-filepond-plugin-image-resize'],
  'bit-filepond-plugin-image-transform': ['bit-filepond-plugin-image-transform'],
  'bit-filepond-plugin-image-validate-size': ['bit-filepond-plugin-image-validate-size'],
  'bit-filepond-plugin-media-preview': ['bit-filepond-plugin-media-preview'],
  'bit-form-abandonment': ['bit-form-abandonment', 'saveFormProgress', 'setFieldValues', 'autoSavePartial'],
  'bit-frontend': ['hidden-token-field', 'bitsFetchFront', 'submit-form', 'customFieldsReset', 'advancedFileHandle', 'hideChildFldHandle', 'decisionFldHandle', 'validate-focus', 'bitform-init', 'bitform-elementor', 'resetPlaceholders', 'bfResetDefaultValue'],
  'bit-helpers': ['observeElm', 'bfSelect', 'bfReset', 'bfSplit', 'setBFMsg', 'bfValidationErrMsg', 'setHiddenFld', 'paymentSubmitResponse', 'isFormValidatedWithoutError', 'setStyleProperty', 'scrollToElm', 'moveToFirstErrFld', 'getFldKeyAndRowIndx', 'replaceFieldAndSmartValues', 'bfDateFieldsLogicCheck', 'bfParseDateTime', 'bfParseSpecialDateFormat', 'bfCalculateDateTimeDifference', 'bfFormatDateTime', 'bfSetDateTimeConfigOption', 'bfAddOrSubtractDateTime', 'initCheckDisableOnMax', 'initAddOtherOpt', 'resetOtherOpt', 'setSliderFieldValue', 'scriptLoader', 'initPaypalFld', 'initRazorpayFld', 'initStripeFld', 'initRecaptchaFld', 'initHCaptchaFld', 'initTurnstileFld', 'initRecaptchaV3Fld'],
  'bit-page-lifecycle': ['bit-page-lifecycle'],
  'bit-paypal-field': ['bit-paypal-field'],
  'bit-phone-number-field': ['bit-phone-number-field'],
  'bit-razorpay-field': ['bit-razorpay-field'],
  'bit-recaptcha-field': ['bit-recaptcha-field'],
  'bit-hcaptcha-field': ['bit-hcaptcha-field'],
  'bit-repeater-field': ['bit-repeater-field', 'checkRepeatedField', 'isRepeaterField', 'getRepeatedIndexes', 'getIndexesBaseOnConditions'],
  'bit-select-field': ['bit-select-field'],
  'bit-stripe-field': ['bit-stripe-field'],
  'bit-mollie-field': ['bit-mollie-field'],
  'bit-validation': ['checkFldValidation', 'checkMinMaxOptions', 'checkMinMaxValue', 'customOptionValidation', 'dcsnbxFldValidation', 'emailFldValidation', 'fileupFldValidation', 'advanceFileUpFldValidation', 'bfDatetimeFldValidation', 'generateBackslashPattern', 'nmbrFldValidation', 'requiredFldValidation', 'urlFldValidation', 'validateForm', 'inputMaskValidation', 'regexPatternValidation', 'phoneNumberFldValidation', 'currencyFldValidation'],
  'bit-virtualized-list': ['bit-virtualized-list'],
  'bit-signature-field': ['bit-signature-field'],
  'bit-multi-step-form': ['bit-multi-step-form'],
  'bit-conversational-form': ['bit-conversational-form', 'handleConversationalFormMsg'],
  'bit-rating-field': ['bit-rating-field'],
  'bit-data-view': ['bit-data-view'],
  'bit-advanced-datetime-field': ['bit-advanced-datetime-field'],
  'bit-fake-filler': ['bit-fake-filler'],
  'bit-input-mask': ['bit-input-mask', 'setBitInputMaskToInput'],
}

export const getPackageFileList = (packageName) => packagesFileLists[packageName] || []
