import templateDemoLink from './templateDemoLink'

export default [
  {
    img: 'blank.png',
    creatable: true,
    title: 'Blank',
    description: 'Create a form from scratch',
    category: 'basic',
    tag: 'blank form, empty form, scratch form',
    source: '',
    fileExistIn: 'self',
    slug: 'blank',
    theme: 'bitformDefault',
    isPro: false,
    isNew: false,
  },
  {
    img: 'contact-form-default.png',
    creatable: true,
    title: 'Contact Form',
    description: 'Contact form for your website.',
    category: 'basic',
    tag: 'contact form, contact us, contact, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'contact_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.contact_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'contact-form-atlassian.png',
    creatable: true,
    title: 'Contact Form (Atlassian Theme)',
    description: 'Contact form for your website using atlassian theme.',
    category: 'basic',
    tag: 'contact form atlassian',
    source: '',
    fileExistIn: 'self',
    slug: 'contact_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.contact_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'simple-contact-form-default.png',
    creatable: true,
    title: 'Simple Contact Form',
    description: 'Simple contact form for your website.',
    category: 'basic',
    tag: 'contact form, simple contact, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'simple_contact_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.simple_contact_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'simple-contact-form-atlassian.png',
    creatable: true,
    title: 'Simple Contact Form (Atlassian Theme)',
    description: 'Simple contact form for your website.',
    category: 'basic',
    tag: 'contact form, atlassian theme, simple contact',
    source: '',
    fileExistIn: 'self',
    slug: 'simple_contact_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.simple_contact_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'signup-form-default.png',
    creatable: true,
    title: 'Signup Form',
    description: 'This form can be used to create signup.',
    category: 'Basic',
    tag: 'signup form, register, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'signup_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.signup_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'signup-form-atlassian.png',
    creatable: true,
    title: 'Signup Form (Atlassian Theme)',
    description: 'This form can be used to create signup by using atlassian theme.',
    category: 'Basic',
    tag: 'signup form, register, atlassian',
    source: '',
    fileExistIn: 'self',
    slug: 'signup_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.signup_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'login-form-default.png',
    creatable: true,
    title: 'Login Form',
    description: 'This form can be used to create login form.',
    category: 'Basic',
    tag: 'login form, login, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'login_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.login_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'login-form-atlassian.png',
    creatable: true,
    title: 'Login Form (Atlassian Theme)',
    description: 'This form can be used to create Login form by atlassian theme.',
    category: 'Basic',
    tag: 'login form, atlassian theme, login',
    source: '',
    fileExistIn: 'self',
    slug: 'login_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.login_form_atlassian,
    isPro: false,
    isNew: false,
  },

  {
    img: 'newsletter-form-default.png',
    creatable: true,
    title: 'Newsletter Form',
    description: 'This form can be used to create newsletters.',
    category: 'Basic',
    tag: 'Newsletter, subscriber, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'newsletter_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.newsletter_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'newsletter-form-atlassian.png',
    creatable: true,
    title: 'Newsletter Form (Atlassian Theme)',
    description: 'This form can be used to create newsletters by atlassian theme.',
    category: 'Basic',
    tag: 'Newsletter form, subscriber form, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'newsletter_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.newsletter_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'newsletter-signup-default.png',
    creatable: true,
    title: 'Newsletter Signup Form',
    description: 'This form can be used to create newsletters.',
    category: 'Basic',
    tag: 'Newsletter, subscriber, signup form, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'newsletter_sing_up_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.newsletter_sign_up_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'newsletter-signup-atlassian.png',
    creatable: true,
    title: 'Newsletter Signup Form (Atlassian Theme)',
    description: 'This form can be used to create newsletters by atlassian theme.',
    category: 'Basic',
    tag: 'Newsletter form, subscriber form, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'newsletter_sing_up_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.newsletter_sign_up_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'meeting-room-default.png',
    creatable: true,
    title: 'Meeting Room Registration Form',
    description: 'This meeting room registration form template, you can simplify the process of requesting meeting rooms whenever you need.',
    category: 'booking',
    tag: 'Meeting registration, room registration, meeting room, registration form, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'meeting_room_reg',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.meeting_room_reg,
    isPro: false,
    isNew: false,
  },
  {
    img: 'meeting-room-atlassian.png',
    creatable: true,
    title: 'Meeting Room Registration Form (Atlassian Theme)',
    description: 'This meeting room registration form template, you can simplify the process of requesting meeting rooms whenever you need.',
    category: 'booking',
    tag: 'Meeting registration, room registration, meeting room, registration form, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'meeting_room_reg_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.meeting_room_reg_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'customer-complain-form.png',
    creatable: true,
    title: 'Customer Complaint Form',
    description: 'Use this form to gether customer feedback and complaints.',
    category: 'Feedback',
    tag: 'feedback form, customer survey, bit form, customer, complain, customer complain',
    source: '',
    fileExistIn: 'self',
    slug: 'customer_complain_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.customer_complain_form,
    isNew: true,
  },
  {
    img: 'customer-complain-form-atlassian.png',
    creatable: true,
    title: 'Customer Complaint Form (Atlassian Theme)',
    description: 'Use this form to gether customer feedback and complaints.',
    category: 'Feedback',
    tag: 'feedback form, customer survey, bit form, customer, complain, customer complain',
    source: '',
    fileExistIn: 'self',
    slug: 'customer_complain_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.customer_complain_form_atlassian,
    isNew: true,
  },
  // {
  //   // img: getTemplateImagePath('newsletter_signup.png'),
  //   creatable: true,
  //   title: 'Test Repeater field',
  //   description: 'This meeting room registration form template, you can simplify the process of requesting meeting rooms whenever you need.',
  //   category: 'education',
  //   tag: 'Meeting registration, room registration, meeting room, registration form',
  //   source: '',
  //   fileExistIn: 'self',
  //   slug: 'repeater_field_test_form',
  //   theme: 'bitformDefault',
  // demoURL: 'https://bitapps.pro/bit-form/form-templates/',
  //   isPro: false,
  //   isNew: false,
  // },
  // {
  //   // img: getTemplateImagePath('newsletter_signup.png'),
  //   creatable: true,
  //   title: 'Test Repeater field atlassian theme',
  //   description: 'This meeting room registration form template, you can simplify the process of requesting meeting rooms whenever you need.',
  //   category: 'education',
  //   tag: 'Meeting registration, room registration, meeting room, registration form',
  //   source: '',
  //   fileExistIn: 'self',
  //   slug: 'repeater_field_test_form_atlassian',
  //   theme: 'atlassian',
  // demoURL: 'https://bitapps.pro/bit-form/form-templates/',
  //   isPro: false,
  //   isNew: false,
  // },
  {
    img: 'grade-book-form-default.png',
    creatable: true,
    title: 'Grade Book Form',
    description: 'This form can be used to submit grades.',
    category: 'education',
    tag: 'registration, grade book, grade, registration form, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'grade_book_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.grade_book_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'grade-book-form-atlassian.png',
    creatable: true,
    title: 'Grade Book Form (Atlassian Theme)',
    description: 'This form can be used to submit grades by using atlassian theme.',
    category: 'education',
    tag: 'registration, grade book, grade, registration form, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'grade_book_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.grade_book_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'academic-advisor-default.png',
    creatable: true,
    title: 'Academic Advisor Meeting Form',
    description: 'Use the academic advisor meeting form template to let students schedule meetings with their academic advisors.',
    category: 'education',
    tag: 'Meeting registration, registration form, academic advisor, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'academic_advisor_meeting_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.academic_advisor_meeting_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'academic-advisor-atlassian.png',
    creatable: true,
    title: 'Academic Advisor Meeting Form (Atlassian Theme)',
    description: 'Use the academic advisor meeting form template to let students schedule meetings with their academic advisors.',
    category: 'education',
    tag: 'Meeting registration, registration form, academic advisor, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'academic_advisor_meeting_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.academic_advisor_meeting_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'conference-room-reg-default.png',
    creatable: true,
    title: 'Conference Registration Form',
    description: 'Managing conferences is challenging work, but the proper form can make your job significantly easier. ',
    category: 'Booking',
    tag: 'Conference registration, registration form, conference, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'conference_reg_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.conference_reg_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'conference-room-reg-atlassian.png',
    creatable: true,
    title: 'Conference Registration Form (Atlassian Theme)',
    description: 'Managing conferences is challenging work, but the proper form can make your job significantly easier. ',
    category: 'Booking',
    tag: 'Conference registration, registration form, conference, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'conference_reg_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.conference_reg_form_atlassian,
    isPro: false,
    isNew: false,
  },
  // {
  //   // img: getTemplateImagePath('newsletter_signup.png'),
  //   creatable: true,
  //   title: 'Pro Template test',
  //   description: 'This form can be used to create newsletters.',
  //   category: 'business',
  //   tag: 'Newsletter, website, tech, subscriber',
  //   source: '',
  //   fileExistIn: 'self',
  //   slug: 'pro_blank_slug',
  //   theme: 'bitformDefault',
  // demoURL: 'https://bitapps.pro/bit-form/form-templates/',
  //   isPro: true,
  //   isNew: false,
  // },
  // {
  //   // img: getTemplateImagePath('newsletter_signup.png'),
  //   creatable: true,
  //   title: 'bitform test confirmation and conditions',
  //   description: 'This form can be used to create newsletters.',
  //   category: 'business',
  //   tag: 'Newsletter, website, tech, subscriber',
  //   source: '',
  //   fileExistIn: 'self',
  //   slug: 'bitform_test_confirmation_conditions',
  //   theme: 'bitformDefault',
  // demoURL: 'https://bitapps.pro/bit-form/form-templates/',
  //   isPro: true,
  //   isNew: false,
  // },
  // {
  //   img: 'buy-me-coffee-default.png',
  //   creatable: true,
  //   title: 'multi step form',
  //   description: 'This form can be used to create newsletters.',
  //   category: 'business',
  //   tag: 'Newsletter, website, tech, subscriber',
  //   source: '',
  //   fileExistIn: 'self',
  //   slug: 'multi_step_form',
  //   theme: 'bitformDefault',
  //   demoURL: 'https://bitapps.pro/bit-form/form-templates/',
  //   isPro: true,
  //   isNew: false,
  //   proRequiredVersion: '2.10.0',
  // },
  {
    img: 'buy-me-coffee-default.png',
    creatable: true,
    title: 'Buy me a coffee form with stripe payment',
    description: 'This form can be used to get payment from your users by stripe.',
    category: 'payment',
    tag: 'payment, stripe, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'buy_me_a_coffee_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.buy_me_a_coffee_form,
    isPro: true,
    proRequiredVersion: '2.8.0',
    isNew: false,
    paymentType: ['Stripe'],
  },
  {
    img: 'buy-me-coffee-atlassian.png',
    creatable: true,
    title: 'Buy me a coffee form template (Atlassian Theme)',
    description: 'This form can be used to get payment from your users by stripe using atlassian theme.',
    category: 'payment',
    tag: 'payment, stripe, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'buy_me_a_coffee_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.buy_me_a_coffee_form_atlassian,
    isPro: true,
    proRequiredVersion: '2.8.0',
    isNew: false,
    paymentType: ['Stripe'],
  },
  {
    img: 'job-application-form.png',
    creatable: true,
    title: 'Job Application Multi Step Form',
    description: 'This form can be used to apply for a job.',
    category: 'Business Operations',
    tag: 'application, apply, reg, registration, job, default theme, multi step, section, signature, business',
    source: '',
    fileExistIn: 'self',
    slug: 'job_application_form',
    theme: 'bitformDefault',
    // demoURL: 'https://bitapps.pro/bit-form/form-templates/',
    isPro: true,
    proRequiredVersion: '2.10.2',
    isNew: true,
  },
  {
    img: 'job-application-form-atlassian.png',
    creatable: true,
    title: 'Job Application Multi Step Form (Atlassian Theme)',
    description: 'This form can be used to apply for a job.',
    category: 'Business Operations',
    tag: 'application, apply, reg, registration, job, atlassian theme, multi step, section, signature, business',
    source: '',
    fileExistIn: 'self',
    slug: 'job_application_form_atlassian',
    theme: 'atlassian',
    // demoURL: 'https://bitapps.pro/bit-form/form-templates/',
    isPro: true,
    proRequiredVersion: '2.10.2',
    isNew: true,
  },
  {
    img: 'GDPR-form-default.png',
    creatable: true,
    title: 'Constant Contact GDPR Form',
    description: 'This form can be used to Constant Contact as a GDPR Form.',
    category: 'basic',
    tag: 'contact form, gdpr form, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'gdpf_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.gdpf_form,
    isPro: false,
    isNew: false,
  },
  {
    img: 'GDPR-form-atlassian.png',
    creatable: true,
    title: 'Constant Contact GDPR Form (Atlassian Theme)',
    description: 'This form can be used to Constant Contact as a GDPR Form using atlassian theme.',
    category: 'basic',
    tag: 'contact form, gdpr form, atlassian theme',
    source: '',
    fileExistIn: 'self',
    slug: 'gdpf_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.gdpf_form_atlassian,
    isPro: false,
    isNew: false,
  },
  {
    img: 'wp-auth-reg-default.png',
    creatable: true,
    title: 'WP User Registration Form',
    description: 'This form can be used to create user registration form for your website.',
    category: 'WP Auth',
    tag: 'user registration form, user registration, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'wp_user_reg_form',
    theme: 'bitformDefault',
    demoURL: templateDemoLink.wp_user_reg_form,
    isPro: true,
    proRequiredVersion: '2.9.1',
  },
  {
    img: 'wp-auth-reg-atlassian.png',
    creatable: true,
    title: 'WP User Registration Form (Atlassian Theme)',
    description: 'This form can be used to create user registration form for your website.',
    category: 'WP Auth',
    tag: 'user registration form, user registration, bit form, bitform, default',
    source: '',
    fileExistIn: 'self',
    slug: 'wp_user_reg_atlassian_form',
    theme: 'atlassian',
    demoURL: templateDemoLink.wp_user_reg_atlassian_form,
    isPro: true,
    proRequiredVersion: '2.9.1',
  },
  {
    img: 'disaster-relief-donation-form-atlassian.png',
    creatable: true,
    title: 'Disaster Relief Donation (Atlassian Theme)',
    description: 'This form can be used to collect donations for disaster relief efforts.',
    category: 'Payment',
    tag: 'donation, disaster relief, atlassian theme, payment form',
    source: '',
    fileExistIn: 'self',
    slug: 'disaster_relief_donation_form_atlassian',
    theme: 'atlassian',
    demoURL: templateDemoLink.wp_user_reg_atlassian_form,
    // isPro: true,
    // proRequiredVersion: '2.9.1',
  },
]
