export default function inputWrapperClasses(fk) {
  return {
    [`.${fk}-fld-wrp`]: {
      display: 'var(--fld-wrp-dis, block)',
      'flex-direction': 'var(--fld-wrp-fdir, row)',
      background: 'var(--fld-wrp-bg, transparent)',
      width: '100%',
      padding: 'var(--fld-wrp-p, 0)',
      margin: 'var(--fld-wrp-m, 0)',
      position: 'relative',
      'box-shadow': 'var(--fld-wrp-sh, none)',
      'border-radius': 'var(--fld-wrp-bdr-rad, 0)',
      border: 'var(--fld-wrp-bdr, medium none)',
      'border-width': 'var(--fld-wrp-bdr-width, 0)',
    },
    [`.${fk}-fld-wrp.fld-hide::after`]: {
      position: 'absolute',
      top: 0,
      left: 0,
      content: '""',
      width: '100%',
      height: '100%',
      'background-color': 'rgba(0, 0, 0, 0.2)',
    },
    [`.${fk}-lbl-wrp`]: {
      width: 'var(--lbl-wrp-width, auto)',
      'align-self': 'var(--lbl-wrp-sa, auto)',
      margin: 'var(--lbl-wrp-m, 0)',
      padding: 'var(--lbl-wrp-p, 0)',
      background: 'var(--lbl-wrp-bg, none)',
    },
    [`.${fk}-lbl`]: {
      background: 'var(--fld-lbl-bg, none)',
      color: 'var(--fld-lbl-c, inherit)',
      'font-size': 'var(--fld-lbl-fs)',
      display: 'flex',
      'align-items': 'center',
      'text-align': 'var(--lbl-al, initial)',
      margin: 'var(--fld-lbl-m, 0)',
      padding: 'var(--fld-lbl-p, 0)',
      'box-shadow': 'var(--fld-lbl-sh, none)',
      'border-radius': 'var(--fld-lbl-bdr-rad, 0)',
      border: 'var(--fld-lbl-bdr, medium none)',
      'border-width': 'var(--fld-lbl-bdr-width, 0)',
    },
    [`.${fk}-sub-titl`]: {
      background: 'var(--sub-titl-bg, none)',
      color: 'var(--sub-titl-c, inherit)',
      'font-size': 'var(--sub-titl-fs)',
      display: 'flex',
      'align-items': 'center',
      'text-align': 'var(--sub-titl-al, initial)',
      padding: 'var(--sub-titl-p, 0)',
      margin: 'var(--sub-titl-m, 0)',
      'box-shadow': 'var(--sub-titl-sh, none)',
      'border-radius': 'var(--sub-titl-bdr-rad, 0)',
      border: 'var(--sub-titl-bdr, medium none)',
      'border-width': 'var(--sub-titl-bdr-width, 0)',
    },
    [`.${fk}-hlp-txt`]: {
      background: 'var(--hlp-txt-bg, none)',
      color: 'var(--hlp-txt-c, inherit)',
      'font-size': 'var(--hlp-txt-fs)',
      display: 'flex',
      'align-items': 'center',
      'text-align': 'var(--hlp-txt-al, init)',
      padding: 'var(--hlp-txt-p, 0)',
      margin: 'var(--hlp-txt-m, 0)',
      'box-shadow': 'var(--hlp-txt-sh, none)',
      'border-radius': 'var(--hlp-txt-bdr-rad, 0)',
      border: 'var(--hlp-txt-bdr, medium none)',
      'border-width': 'var(--hlp-txt-bdr-width, 0)',
    },

    [`.${fk}-inp-wrp`]: { width: 'var(--inp-wrp-width, auto)' },
    [`.${fk}-lbl-pre-i`]: {
      width: '15px',
      height: '15px',
    },
    [`.${fk}-lbl-suf-i`]: {
      width: '15px',
      height: '15px',
    },
    [`.${fk}-sub-titl-pre-i`]: {
      width: '11px',
      height: '11px',
    },
    [`.${fk}-sub-titl-suf-i`]: {
      width: '11px',
      height: '11px',
    },
    [`.${fk}-hlp-txt-pre-i`]: {
      width: '11px',
      height: '11px',
    },
    [`.${fk}-hlp-txt-suf-i`]: {
      width: '11px',
      height: '11px',
    },
    [`.${fk}-err-msg`]: {
      background: 'var(--err-bg, none)',
      color: 'var(--err-c, inherit)',
      'font-size': 'var(--err-txt-fs)',
      display: 'flex',
      'align-items': 'center',
      'text-align': 'var(--err-txt-al, init)',
      padding: 'var(--err-p, 0)',
      margin: 'var(--err-m, 0)',
      'box-shadow': 'var(--err-sh, none)',
      'border-radius': 'var(--err-bdr-rad, 0)',
      border: 'var(--err-bdr, medium none)',
      'border-width': 'var(--err-bdr-width, 0)',
    },
    [`.${fk}-err-txt-pre-i`]: {
      width: '11px',
      height: '11px',
      margin: '5px',
    },
    [`.${fk}-err-txt-suf-i`]: {
      width: '11px',
      height: '11px',
      margin: '5px',
    },
  }
}
