export default function inputWrapperClasses(fk) {
  return {
    [`.${fk}-fld-wrp`]: {
      display: 'var(--fld-wrp-dis, block)',
      'flex-direction': 'var(--fld-wrp-fdir, row)',
      'background-color': 'var(--fld-wrp-bg, transparent)',
      padding: 'var(--fld-wrp-p, 0)',
      margin: 'var(--fld-wrp-m, 0)',
      position: 'relative',
      'box-shadow': 'var(--fld-wrp-sh, none)',
      'border-style': 'var(--fld-wrp-bdr, medium)',
      'border-color': 'var(--fld-wrp-bdr-clr, none)',
      'border-radius': 'var(--fld-wrp-bdr-rad, 0)',
      'border-width': 'var(--fld-wrp-bdr-width, 0)',
    },
    [`.${fk}-fld-wrp.fld-hide::after`]: {
      position: 'absolute',
      top: 0,
      left: 0,
      content: '""',
      width: '100%',
      height: '100%',
      'background-color': 'hsla(0, 0%, 0%, 20%)',
    },
    [`.${fk}-lbl-wrp`]: {
      width: 'var(--lbl-wrp-width, auto)',
      'align-self': 'var(--lbl-wrp-sa, auto)',
      margin: 'var(--lbl-wrp-m, 0)',
      padding: 'var(--lbl-wrp-p, 0)',
      'background-color': 'var(--lbl-wrp-bg, none)',
      'box-shadow': 'var(--lbl-wrp-sh, none)',
      'border-style': 'var(--lbl-wrp-bdr, medium)',
      'border-color': 'var(--lbl-wrp-bdr-clr, none)',
      'border-radius': 'var(--lbl-wrp-bdr-rad, 0)',
      'border-width': 'var(--lbl-wrp-bdr-width, 0)',
    },
    [`.${fk}-lbl`]: {
      'background-color': 'var(--fld-lbl-bg, none)',
      color: 'var(--fld-lbl-c, inherit)',
      'font-size': 'var(--fld-lbl-fs)',
      display: 'flex',
      'align-items': 'center',
      // 'text-align': 'var(--lbl-al, initial)',
      'justify-content': 'var(--lbl-al, initial)',
      margin: 'var(--fld-lbl-m, 0)',
      padding: 'var(--fld-lbl-p, 0)',
      'box-shadow': 'var(--fld-lbl-sh, none)',
      'border-style': 'var(--fld-lbl-bdr, medium)',
      'border-color': 'var(--fld-lbl-bdr-clr, none)',
      'border-radius': 'var(--fld-lbl-bdr-rad, 0)',
      'border-width': 'var(--fld-lbl-bdr-width, 0)',
      width: '100%',
      'font-weight': 'var(--lbl-font-w)',
      'font-style': 'var(--lbl-font-style)',
      position: 'var(--fld-lbl-pn,unset)',
    },
    [`.${fk}-req-smbl`]: {
      color: 'var(--req-smbl-c, inherit)',
      'font-size': 'var(--req-smbl-fs)',
      margin: 'var(--req-smbl-m, 0)',
      padding: 'var(--req-smbl-p, 0)',
      'font-weight': 'var(--req-smbl-fw)',
      'line-height': 'var(--req-smbl-lh, 12px)',
      position: 'var(--req-smbl-pn,unset)',
      right: 'var(--req-smbl-rt,unset)',
      left: 'var(--req-smbl-lt,unset)',
    },
    [`.${fk}-sub-titl`]: {
      'background-color': 'var(--sub-titl-bg, none)',
      color: 'var(--sub-titl-c, inherit)',
      'font-size': 'var(--sub-titl-fs)',
      display: 'flex',
      'align-items': 'center',
      // 'text-align': 'var(--sub-titl-al, initial)',
      'justify-content': 'var(--sub-titl-al, initial)',
      padding: 'var(--sub-titl-p, 0)',
      margin: 'var(--sub-titl-m, 0)',
      'box-shadow': 'var(--sub-titl-sh, none)',
      'border-style': 'var(--sub-titl-bdr, medium)',
      'border-color': 'var(--sub-titl-bdr-clr, none)',
      'border-radius': 'var(--sub-titl-bdr-rad, 0)',
      'border-width': 'var(--sub-titl-bdr-width, 0)',
      width: '100%',
      'font-weight': 'var(--sub-titl-font-w)',
      'font-style': 'var(--sub-titl-font-style)',
    },
    [`.${fk}-hlp-txt`]: {
      'background-color': 'var(--hlp-txt-bg, none)',
      color: 'var(--hlp-txt-c, inherit)',
      'font-size': 'var(--hlp-txt-fs)',
      display: 'flex',
      'align-items': 'center',
      // 'text-align': 'var(--hlp-txt-al, init)',
      'justify-content': 'var(--hlp-txt-al, initial)',
      padding: 'var(--hlp-txt-p, 0)',
      margin: 'var(--hlp-txt-m, 0)',
      'box-shadow': 'var(--hlp-txt-sh, none)',
      'border-style': 'var(--hlp-txt-bdr, medium)',
      'border-color': 'var(--hlp-txt-bdr-clr, none)',
      'border-radius': 'var(--hlp-txt-bdr-rad, 0)',
      'border-width': 'var(--hlp-txt-bdr-width, 0)',
      width: '100%',
      'font-weight': 'var(--hlp-txt-font-w)',
      'font-style': 'var(--hlp-txt-font-style)',
    },

    [`.${fk}-inp-wrp`]: { /* width: 'var(--inp-wrp-width, auto)' */ },

    [`.${fk}-lbl-pre-i`]: {
      width: 'var(--lbl-pre-i-w)',
      height: 'var(--lbl-pre-i-h)',
      margin: 'var(--lbl-pre-i-m)',
      padding: 'var(--lbl-pre-i-p)',
      'box-shadow': 'var(--lbl-pre-i-sh, none)',
      'border-style': 'var(--lbl-pre-i-bdr, medium)',
      'border-color': 'var(--lbl-pre-i-bdr-clr, none)',
      'border-width': 'var(--lbl-pre-i-bdr-width, 0)',
      'border-radius': 'var(--lbl-pre-i-bdr-rad, 0)',
      filter: 'var(--lbl-pre-i-fltr)',
    },
    [`.${fk}-lbl-suf-i`]: {
      width: 'var(--lbl-suf-i-w)',
      height: 'var(--lbl-suf-i-h)',
      margin: 'var(--lbl-suf-i-m)',
      padding: 'var(--lbl-suf-i-p)',
      'box-shadow': 'var(--lbl-suf-i-sh, none)',
      'border-style': 'var(--lbl-suf-i-bdr, medium)',
      'border-color': 'var(--lbl-suf-i-bdr-clr, none)',
      'border-width': 'var(--lbl-suf-i-bdr-width, 0)',
      'border-radius': 'var(--lbl-suf-i-bdr-rad, 0)',
      filter: 'var(--lbl-suf-i-fltr)',
    },
    [`.${fk}-sub-titl-pre-i`]: {
      width: 'var(--sub-titl-pre-i-w)',
      height: 'var(--sub-titl-pre-i-h)',
      margin: 'var(--sub-titl-pre-i-m)',
      padding: 'var(--sub-titl-pre-i-p)',
      'box-shadow': 'var(--sub-titl-pre-i-sh, none)',
      'border-style': 'var(--sub-titl-pre-i-bdr, medium)',
      'border-color': 'var(--sub-titl-pre-i-bdr-clr, none)',
      'border-width': 'var(--sub-titl-pre-i-bdr-width, 0)',
      'border-radius': 'var(--sub-titl-pre-i-bdr-rad, 0)',
      filter: 'var(--sub-titl-pre-i-fltr)',
    },
    [`.${fk}-sub-titl-suf-i`]: {
      width: 'var(--sub-titl-suf-i-w)',
      height: 'var(--sub-titl-suf-i-h)',
      margin: 'var(--sub-titl-suf-i-m)',
      padding: 'var(--sub-titl-suf-i-p)',
      'box-shadow': 'var(--sub-titl-suf-i-sh, none)',
      'border-style': 'var(--sub-titl-suf-i-bdr, medium)',
      'border-color': 'var(--sub-titl-suf-i-bdr-clr, none)',
      'border-width': 'var(--sub-titl-suf-i-bdr-width, 0)',
      'border-radius': 'var(--sub-titl-suf-i-bdr-rad, 0)',
      filter: 'var(--sub-titl-suf-i-fltr)',
    },
    [`.${fk}-hlp-txt-pre-i`]: {
      width: 'var(--hlp-txt-pre-i-w)',
      height: 'var(--hlp-txt-pre-i-h)',
      margin: 'var(--hlp-txt-pre-i-m)',
      padding: 'var(--hlp-txt-pre-i-p)',
      'box-shadow': 'var(--hlp-txt-pre-i-sh, none)',
      'border-style': 'var(--hlp-txt-pre-i-bdr, medium)',
      'border-color': 'var(--hlp-txt-pre-i-bdr-clr, none)',
      'border-width': 'var(--hlp-txt-pre-i-bdr-width, 0)',
      'border-radius': 'var(--hlp-txt-pre-i-bdr-rad, 0)',
      filter: 'var(--hlp-txt-pre-i-fltr)',
    },
    [`.${fk}-hlp-txt-suf-i`]: {
      width: 'var(--hlp-txt-suf-i-w)',
      height: 'var(--hlp-txt-suf-i-h)',
      margin: 'var(--hlp-txt-suf-i-m)',
      padding: 'var(--hlp-txt-suf-i-p)',
      'box-shadow': 'var(--hlp-txt-suf-i-sh, none)',
      'border-style': 'var(--hlp-txt-suf-i-bdr, medium)',
      'border-color': 'var(--hlp-txt-suf-i-bdr-clr, none)',
      'border-width': 'var(--hlp-txt-suf-i-bdr-width, 0)',
      'border-radius': 'var(--hlp-txt-suf-i-bdr-rad, 0)',
      filter: 'var(--hlp-txt-suf-i-fltr)',
    },
    [`.${fk}-err-msg`]: {
      'background-color': 'var(--err-bg, none)',
      color: 'var(--err-c, inherit)',
      'font-size': 'var(--err-txt-fs)',
      display: 'flex',
      'align-items': 'center',
      'text-align': 'var(--err-txt-al, init)',
      padding: 'var(--err-p, 0)',
      margin: 'var(--err-m, 0)',
      'box-shadow': 'var(--err-sh, none)',
      'border-style': 'var(--err-bdr, medium)',
      'border-color': 'var(--err-bdr-clr, none)',
      'border-radius': 'var(--err-bdr-rad, 0)',
      'border-width': 'var(--err-bdr-width, 0)',
      'font-weight': 'var(--err-txt-font-w)',
      'font-style': 'var(--err-txt-font-style)',
    },
    [`.${fk}-err-txt-pre-i`]: {
      width: 'var(--err-txt-pre-i-w)',
      height: 'var(--err-txt-pre-i-h)',
      margin: 'var(--err-txt-pre-i-m)',
      padding: 'var(--err-txt-pre-i-p)',
      'box-shadow': 'var(--err-txt-pre-i-sh, none)',
      'border-style': 'var(--err-txt-pre-i-bdr, medium)',
      'border-color': 'var(--err-txt-pre-i-bdr-clr, none)',
      'border-width': 'var(--err-txt-pre-i-bdr-width, 0)',
      'border-radius': 'var(--err-txt-pre-i-bdr-rad, 0)',
      filter: 'var(--err-txt-pre-i-fltr)',
    },
    [`.${fk}-err-txt-suf-i`]: {
      width: 'var(--err-txt-suf-i-w)',
      height: 'var(--err-txt-suf-i-h)',
      margin: 'var(--err-txt-suf-i-m)',
      padding: 'var(--err-txt-suf-i-p)',
      'box-shadow': 'var(--err-txt-suf-i-sh, none)',
      'border-style': 'var(--err-txt-suf-i-bdr, medium)',
      'border-color': 'var(--err-txt-suf-i-bdr-clr, none)',
      'border-width': 'var(--err-txt-suf-i-bdr-width, 0)',
      'border-radius': 'var(--err-txt-suf-i-bdr-rad, 0)',
      filter: 'var(--err-txt-suf-i-fltr)',
    },
  }
}
